# Copyright (C) 2003-2008 Kouichirou Eto, All rights reserved.
# This is free software with ABSOLUTELY NO WARRANTY.
# You can redistribute it and/or modify it under the terms of the GNU GPL 2.

require 'rake'

task :extract do
  sh 'ruby dev-extract-catalog.rb .'
  sh 'cat catalog-ja.txt catalog-ml-ja.txt > interfaces.txt'
end

