# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_edit
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div, {:class=>"header"}, [:h1]],
    [:"!--", "header"],
    [:div,
     {:class=>"main"},
     [:div, {:class=>"edit"}],
     [:"!--", "edit"],
     [:div, {:class=>"attach"}],
     [:"!--", "attach"]],
    [:"!--", "main"],
    [:div,
     {:class=>"sidebar"},
     [:div, {:class=>"edit_help"}],
     [:"!--", "edit_help"],
     [:div, {:class=>"edit_history"}],
     [:"!--", "edit_history"]],
    [:"!--", "sidebar"],
    [:div, {:class=>"footer"}],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
