# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_editor
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head,
   [:link,
    {:rel=>"stylesheet",
     :href=>".theme/css/base.css",
     :type=>"text/css",
     :media=>"screen,tv"}],
   [:link,
    {:rel=>"stylesheet",
     :href=>".theme/qwikeditor/qwikeditor.css",
     :type=>"text/css",
     :media=>"screen,tv"}]],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div, {:class=>"header"}, [:h1]],
    [:"!--", "header"],
    [:div, {:class=>"message"}],
    [:"!--", "message"],
    [:div, {:class=>"main"}],
    [:"!--", "main"],
    [:div, {:class=>"sidebar"}],
    [:"!--", "sidebar"],
    [:div,
     {:class=>"footer"},
     "powered by ",
     [:a, {:href=>"http://qwik.jp/"}, "qwikWeb"]],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
