# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_notice
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head,
   [:link,
    {:media=>"screen,tv",
     :href=>".theme/css/base.css",
     :type=>"text/css",
     :rel=>"stylesheet"}],
   [:link,
    {:media=>"screen,tv",
     :href=>".theme/qwiknotice/qwiknotice.css",
     :type=>"text/css",
     :rel=>"stylesheet"}]],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div, {:class=>"header"}, [:h1]],
    [:"!--", "header"],
    [:div, {:class=>"day"}, [:div, {:class=>"section"}], [:"!--", "section"]],
    [:"!--", "day"],
    [:div,
     {:class=>"footer"},
     "powered by ",
     [:a, {:href=>"http://qwik.jp/"}, "qwikWeb"],
     [:span, {:title=>"__qwik_page_generate_time__"}, " "]],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
