# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_plain
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head,
   [:link,
    {:type=>"text/css",
     :media=>"screen,tv",
     :rel=>"stylesheet",
     :href=>".theme/css/base.css"}],
   [:link,
    {:type=>"text/css",
     :media=>"screen,tv",
     :rel=>"stylesheet",
     :href=>".theme/qwikplain/qwikplain.css"}]],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div, {:class=>"header"}, [:h1]],
    [:"!--", "header"],
    [:div, {:class=>"main"}],
    [:"!--", "main"],
    [:div,
     {:class=>"footer"},
     [:span,
      {:title=>"__qwik_page_generate_time__"},
      "powered by ",
      [:a, {:href=>"http://qwik.jp/"}, "qwikWeb"]]],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
