# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_surface
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head,
   [:link,
    {:media=>"screen,tv",
     :href=>".theme/css/base.css",
     :type=>"text/css",
     :rel=>"stylesheet"}]],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div,
     {:class=>"main"},
     [:div, {:id=>"adminmenu", :class=>"adminmenu"}],
     [:"!--", "adminmenu"],
     [:div, {:id=>"toc", :class=>"toc"}],
     [:"!--", "toc"],
     [:h1],
     [:div, {:class=>"body_enter"}],
     [:"!--", "body_enter"],
     [:div, {:class=>"body_main"}],
     [:"!--", "body_main"],
     [:div, {:id=>"body_leave", :class=>"body_leave"}],
     [:"!--", "body_leave"]],
    [:"!--", "main"],
    [:div, {:class=>"sidebar"}],
    [:"!--", "sidebar"],
    [:div,
     {:class=>"footer"},
     "powered by ",
     [:a, {:href=>"http://qwik.jp/"}, "qwikWeb"],
     [:span, {:title=>"__qwik_page_generate_time__"}, " "]],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
