# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_system
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head, {:id=>"header"}],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div, {:class=>"header"}, [:div, [:div, [:h1, {:id=>"view_title"}]]]],
    [:"!--", "header"],
    [:div,
     {:class=>"update day"},
     [:div,
      {:class=>"form"},
      [:div, {:id=>"msg", :class=>"msg"}],
      [:"!--", "msg"],
      [:div, {:id=>"differ", :class=>"differ"}],
      [:"!--", "differ"],
      [:div, {:id=>"editor", :class=>"editor"}],
      [:"!--", "editor"]],
     [:"!--", "form"]],
    [:"!--", "update day"],
    [:div,
     {:class=>"update day"},
     [:div,
      {:class=>"comment"},
      [:div, {:id=>"editorfooter", :class=>"commentbody"}],
      [:"!--", "commentbody"]],
     [:"!--", "comment- "]],
    [:"!--", "update day"],
    [:div, {:id=>"footer", :class=>"footer"}],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
