# This file is automatically generated.
# DO NOT EDIT THIS FILE.

module Qwik
  class Template
    def self.generate_view
      return [[:"!DOCTYPE",
  "html",
  "PUBLIC",
  "-//W3C//DTD HTML 4.01 Transitional//EN",
  "http://www.w3.org/TR/html4/loose.dtd"],
 [:html,
  [:head, {:id=>"header"}],
  [:body,
   {:onload=>"qwik_onload();"},
   [:div,
    {:class=>"container"},
    [:div,
     {:class=>"main"},
     [:div, {:id=>"adminmenu", :class=>"adminmenu"}],
     [:"!--", "adminmenu"],
     [:div, {:id=>"toc", :class=>"toc"}],
     [:"!--", "toc"],
     [:h1, {:id=>"view_title"}],
     [:div, {:id=>"body_enter"}],
     [:"!--", "id:body_enter"],
     [:div, {:id=>"body"}],
     [:"!--", "id:body"],
     [:div, {:id=>"body_leave"}],
     [:"!--", "id:body_leave"]],
    [:"!--", "main"],
    [:div, {:id=>"sidemenu", :class=>"sidebar"}],
    [:"!--", "sidebar"],
    [:div, {:id=>"footer", :class=>"footer"}],
    [:"!--", "footer"]],
   [:"!--", "container"]]]]

    end
  end
end
